# -*- coding: utf-8 -*-
"""carboncalc

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VAYM1GyukG18e41Xq8pVwg_MuU9-66Q6
"""
# 1. Tulis isi file dashboard ke carboncalc.py
code = '''\
import streamlit as st
import matplotlib.pyplot as plt
from streamlit_extras.metric_cards import style_metric_cards

st.set_page_config(page_title="CarbonCalc", layout="wide", page_icon="🌿")

st.markdown("""
    <style>
    html, body, .main, .block-container {
        background: linear-gradient(135deg, #e0f7fa, #ffffff);
    }
    .main-title {
        font-size: 32px;
        font-weight: bold;
        color: #2c3e50;
        margin-top: 10px;
    }
    .subtext {
        font-size: 16px;
        color: #34495e;
        margin-top: -10px;
        margin-bottom: 25px;
    }
    .box-style {
        background-color: rgba(255, 255, 255, 0.95);
        padding: 20px;
        border-left: 6px solid #74c69d;
        border-radius: 10px;
        margin-bottom: 20px;
    }
    </style>
""", unsafe_allow_html=True)

# Gambar header (pastikan file cobaa.png sudah diupload di sesi)
st.image("cobaa.png", width=800)

# Judul dan subjudul
st.markdown("<div class='main-title'>🌿 CarbonCalc: Your Personal Carbon Footprint Tracker</div>", unsafe_allow_html=True)
st.markdown("<div class='subtext'>Understand how your daily habits impact the planet — visually, personally, and powerfully.</div>", unsafe_allow_html=True)

# Video edukasi pembuka
st.markdown(\"""
### 🎬 What is a Carbon Footprint?
Before you start calculating, let's explore what a carbon footprint really means — and why every little action matters 🌎
\""")
st.video("https://www.youtube.com/watch?v=_6xlNyWPpB8")

with st.expander("🌍 Why It Matters"):
    st.markdown("""
### 💥 Climate crisis is real
- Heatwaves, floods, and pollution are rising.
- Many don’t realize how their lifestyle affects emissions.

### 🔍 The Problem:
> Most tools are too generic. We need something personal, data-based, and easy.
""")

with st.expander("✅ Our Solution: CarbonCalc"):
    st.markdown("""
- Calculates your weekly CO₂e based on real habits
- Categories: transport, food, energy, consumption
- Visualizes your top emission sources
""")

with st.expander("📖 How to Use"):
    st.markdown("""
1. Fill in your daily habits on the sidebar.
2. Click the button.
3. View your emissions, category breakdown, and badge.
""")

st.divider()

st.sidebar.header("📝 Your Daily Habits")
motor_km = st.sidebar.slider("🛵 Motorbike (km/day)", 0, 50, 10)
car_km = st.sidebar.slider("🚗 Car (km/day)", 0, 50, 5)
meat_meals = st.sidebar.slider("🥩 Meat meals (per week)", 0, 21, 4)
packaged_foods = st.sidebar.slider("🍜 Instant food (per week)", 0, 20, 6)
ac_hours = st.sidebar.slider("❄️ AC usage (hours/day)", 0, 24, 6)
electricity = st.sidebar.selectbox("⚡ Monthly electricity (kWh)", ["<200", "200–500", ">500"])
online_shopping = st.sidebar.slider("📦 Online shopping (per week)", 0, 10, 2)
plastic_items = st.sidebar.slider("🧃 Single-use plastics (per week)", 0, 20, 5)

if st.sidebar.button("🚀 Calculate My Carbon Footprint"):
    co2 = (
        motor_km * 0.1 + car_km * 0.2 +
        meat_meals * 3 + packaged_foods * 0.2 +
        ac_hours * 0.15 +
        {"<200": 5, "200–500": 10, ">500": 15}[electricity] +
        online_shopping * 0.3 + plastic_items * 0.1
    )

    st.markdown(f"""
    <div class='box-style'>
        <h3>📊 Your Weekly Carbon Emission:</h3>
        <p><b>{co2:.2f} kg CO₂e</b></p>
        <p style='font-size:14px;color:#333;'>✅ Sustainable target: less than <b>5 kg CO₂e/week</b>.</p>
        <p style='font-style:italic;color:#4a7c59;'>🌟 Every small step matters. Thank you for making a difference!</p>
    </div>
    """, unsafe_allow_html=True)

    if co2 < 5:
        st.success("🌱 Green Champion – Your impact is very low!")
    elif co2 <= 10:
        st.info("🌤️ Fair – Good start, let's reduce more!")
    else:
        st.error("🔥 High Impact – Time to take action!")

    labels = ['Transport', 'Food', 'Energy', 'Consumption']
    values = [
        motor_km * 0.1 + car_km * 0.2,
        meat_meals * 3 + packaged_foods * 0.2,
        ac_hours * 0.15 + {"<200": 5, "200–500": 10, ">500": 15}[electricity],
        online_shopping * 0.3 + plastic_items * 0.1
    ]
    fig, ax = plt.subplots()
    ax.pie(values, labels=labels, autopct='%1.1f%%', startangle=90)
    ax.axis('equal')
    st.pyplot(fig)

    st.info("Thanks for using CarbonCalc! Every small step counts 🌎")

st.divider()
st.subheader("💬 Ask CarbonCalc")
st.markdown("Curious about your emissions or how to reduce them? Ask me anything!")

if "chat_history" not in st.session_state:
    st.session_state.chat_history = []

user_input = st.chat_input("Type your question here...")

if user_input:
    if "meat" in user_input.lower():
        bot_reply = "🥩 Eating less red meat is one of the best ways to lower your carbon footprint!"
    elif "ac" in user_input.lower():
        bot_reply = "❄️ Reducing AC usage or using energy-efficient units helps a lot!"
    elif "bike" in user_input.lower():
        bot_reply = "🚴 Using a bike instead of a car is awesome — zero carbon!"
    elif "plastic" in user_input.lower():
        bot_reply = "🧃 Try using reusable bags and bottles to reduce plastic waste."
    else:
        bot_reply = "🌱 That's a great question! Try being more specific about your habits."

    st.session_state.chat_history.append(("You", user_input))
    st.session_state.chat_history.append(("CarbonCalc", bot_reply))

for sender, msg in st.session_state.chat_history:
    st.chat_message(sender).write(msg)

st.markdown("""
<hr style="border:1px solid #ccc">
<div style='text-align: center; padding-top: 10px; padding-bottom: 20px;'>
    <p style='font-size: 16px;'>👩‍💻 <strong>Created with data and 💚 by:</strong></p>
    <p style='font-size: 17px;'>🌱 <em>CarbonCalc Team</em></p>
    <p style='font-size: 15px;'>
        👩‍🏫 Nurhidayah &nbsp;&nbsp;|&nbsp;&nbsp;
        👩‍🔬 Oktiviyani Daswati &nbsp;&nbsp;|&nbsp;&nbsp;
        👩 Siti Mutiah &nbsp;&nbsp;|&nbsp;&nbsp;
        👩 Yunia Hasnataeni
    </p>
    <p style='font-size: 14px; color: gray; margin-top: 10px;'>📍 Presented for <strong>GYIC 2025</strong></p>
</div>
""", unsafe_allow_html=True)
'''

with open("carboncalc.py", "w") as f:
    f.write(code)

# 2. Run streamlit & expose via ngrok
from pyngrok import ngrok
import time, threading

ngrok.set_auth_token("2zMNXLGTdKjdXD88EzG1eCufrs0_3aXmqnevjddytjFQqo2bs")

def run():
    streamlit run carboncalc.py

threading.Thread(target=run).start()
time.sleep(4)
public_url = ngrok.connect(8501)
print("✅ Your CarbonCalc Dashboard is live at:")
print(public_url)
